version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-v1-{{ checksum "gradle/libs.versions.toml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Run quality gate
          command: ./gradlew lint test assembleRelease bundleRelease
      - save_cache:
          key: gradle-v1-{{ checksum "gradle/libs.versions.toml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: release-apk
      - store_artifacts:
          path: app/build/outputs/bundle/release/
          destination: release-bundle
